
import { Product, Category, Cart, Order, User, PaymentRecord, Campaign } from '@/types';
import { SEED_PRODUCTS, SEED_CATEGORIES, SEED_USERS } from './seedData';
import { auditService } from '@/lib/audit/auditLogger';
import { eventBus } from '@/lib/events/eventBus';

class MockDatabase {
  public products: Product[] = [...SEED_PRODUCTS];
  public categories: Category[] = [...SEED_CATEGORIES];
  public users: (User & { passwordHash: string })[] = [...SEED_USERS];
  public carts: Map<string, Cart> = new Map();
  public orders: Order[] = [
    {
      id: 'ord_init_01',
      orderNumber: 'NEX-ORD-98210',
      userId: 'usr_customer_01',
      userEmail: 'customer@razoragent.ai',
      userName: 'Elena Rostova (AI Buyer)',
      subtotal: 55397,
      discount: 5539,
      tax: 3988,
      shipping: 0,
      total: 53846,
      currency: 'INR',
      status: 'PAID',
      paymentMethod: 'UPI',
      isAiAssisted: true,
      items: [
        {
          id: 'item_01',
          productId: 'prod_03',
          productName: 'RazorAgent SwiftAir 14" Slim College Edition',
          quantity: 1,
          unitPrice: 49999,
          totalPrice: 49999,
          image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&auto=format&fit=crop&q=80'
        },
        {
          id: 'item_02',
          productId: 'prod_05',
          productName: 'AeroGlide Pro Wireless Ergonomic Mouse',
          quantity: 1,
          unitPrice: 2499,
          totalPrice: 2499,
          image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&auto=format&fit=crop&q=80'
        },
        {
          id: 'item_03',
          productId: 'prod_07',
          productName: 'AcousticPure Flow ANC Wireless Headphones',
          quantity: 1,
          unitPrice: 2899,
          totalPrice: 2899,
          image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80'
        }
      ],
      shippingAddress: {
        fullName: 'Elena Rostova',
        addressLine1: 'Tech Residency, Tower B, 4th Floor',
        city: 'Bengaluru',
        state: 'Karnataka',
        postalCode: '560100',
        country: 'India',
        phone: '+91 98765 43210'
      },
      timeline: [
        { status: 'CREATED', timestamp: '2026-08-30T10:00:00.000Z', message: 'Order generated by AI agent bundle recommendation.' },
        { status: 'PENDING_PAYMENT', timestamp: '2026-08-30T10:00:05.000Z', message: 'Razorpay sandbox checkout session prepared.' },
        { status: 'PAID', timestamp: '2026-08-30T10:01:12.000Z', message: 'Payment of ₹53,846 verified via Razorpay sandbox webhook.' },
        { status: 'PROCESSING', timestamp: '2026-08-30T10:15:00.000Z', message: 'Sent to automated warehouse fulfillment.' }
      ],
      createdAt: '2026-08-30T10:00:00.000Z',
      updatedAt: '2026-08-30T10:15:00.000Z'
    }
  ];
  public payments: PaymentRecord[] = [
    {
      id: 'pay_init_01',
      orderId: 'ord_init_01',
      razorpayOrderId: 'order_test_razoragent_98210',
      razorpayPaymentId: 'pay_test_razoragent_succ_110',
      razorpaySignature: 'sig_mock_verified_hmac_2026',
      amount: 53846,
      currency: 'INR',
      status: 'CAPTURED',
      method: 'UPI',
      createdAt: '2026-08-30T10:01:12.000Z'
    }
  ];
  public campaigns: Campaign[] = [
    {
      id: 'camp_01',
      merchantId: 'merch_01',
      title: 'College AI Creator Setup Blast',
      goal: 'Drive ₹5,00,000 in student bundle GMV',
      targetAudience: 'Engineering & CS college students with interest in lightweight laptops & ANC headphones',
      budget: 25000,
      status: 'ACTIVE',
      strategy: JSON.stringify({
        primaryOffer: '10% OFF bundled accessories with SwiftAir 14',
        upsellTrigger: 'Suggest 32GB RAM version for heavy Docker users (+₹10,000)',
        channels: ['AI Chat In-Stream Recommendation', 'Smart Shop Highlight']
      }),
      schedule: JSON.stringify({ startDate: '2026-08-25', endDate: '2026-09-15' }),
      metrics: JSON.stringify({ impressions: 14200, conversions: 38, revenueGenerated: 2045000 }),
      createdAt: '2026-08-25T00:00:00.000Z',
      updatedAt: '2026-08-30T00:00:00.000Z'
    }
  ];

  // Helper Methods
  public getOrCreateCart(sessionId: string, userId?: string): Cart {
    let cart = this.carts.get(sessionId);
    if (!cart) {
      cart = {
        id: 'cart_' + Math.random().toString(36).substring(2, 9),
        userId,
        sessionId,
        items: [],
        subtotal: 0,
        discount: 0,
        tax: 0,
        shipping: 0,
        total: 0,
        status: 'ACTIVE',
        updatedAt: new Date().toISOString()
      };
      this.carts.set(sessionId, cart);
    }
    return cart;
  }

  public recalculateCart(cart: Cart, couponCode?: string): Cart {
    let subtotal = 0;
    cart.items.forEach(item => {
      item.totalPrice = item.unitPrice * item.quantity;
      subtotal += item.totalPrice;
    });

    cart.subtotal = subtotal;
    let discount = 0;
    if (couponCode) {
      const code = couponCode.toUpperCase();
      if (code === 'STUDENT10' || code === 'NEXORA10') {
        discount = Math.round(subtotal * 0.1);
        cart.couponCode = code;
      } else if (code === 'SAVE2000' && subtotal > 10000) {
        discount = 2000;
        cart.couponCode = code;
      }
    }
    cart.discount = discount;
    const taxableAmount = Math.max(0, subtotal - discount);
    cart.tax = Math.round(taxableAmount * 0.08); // 8% GST/Tax
    cart.shipping = subtotal > 2000 || subtotal === 0 ? 0 : 150;
    cart.total = taxableAmount + cart.tax + cart.shipping;
    cart.updatedAt = new Date().toISOString();

    return cart;
  }
}

const globalForMockDb = global as unknown as { mockDb: MockDatabase };
export const mockDb = globalForMockDb.mockDb || new MockDatabase();
if (process.env.NODE_ENV !== 'production') globalForMockDb.mockDb = mockDb;
